console.log("Zeeshan Siddiqui")
console.log(2005)
console.log("2005")
console.log("abc","cde","fgh")
console.log("Zeeshan Siddiqui",(2005))
console.log("Zeeshan Siddqui (2005)")
console.log("Zeeshan","Siddqui","(2005)")
console.log("zeeshan")
console.log("Siddiqui")
console.log((2005))
console.log("zeeshan"+"Sid"+2005)
console.log("zeeshan","Siddqui","(2005)")